### ISSUE TITLE
in table of contents, on right side, only show categories: coffee shop, bar, demo box, storefront. in this order: demo box, storefront, coffee shop, bar

### ISSUE THREAD

**Issue by ezl** [howdykolache/admin#74]
Currently, I believe the right side iterates over ALL client types, in order:
1. coffee shop
2. bar
3. etc
4. etc

instead, ONLY show these categories, in this order:
1. demo box
2. storefront
3. coffee shop
4. bar

Reasoning - these are categories for which there is IMPLICIT, recurring knowledge about how/when these things will be packaged and presented. therefore they are a special case. the other ones (catering and client orders) require additional information, so those will always be added via the "Admin Create Order" page

**Comment by niall-p-gray** [comment]
Completed, but this one has a few implication, so I've dropped some notes below:

- I've tweaked the ordering by changing the numbering in the 'Client Type' options themselves (which have explicit values of '1. Demo Box', '2. Storefront', etc in Airtable). This will likely affect the ordering of the client grouping on other pages (the delivery summary page perhaps being a good example) - if this is negligible all good, and if not I'm wondering if it's better to branch the client type data out into its own tab so we can store dedicated data against each of the client types (ordering on TOC, ordering on delivery summary, display on TOC, wholesale or admin, etc) and everything can then be pulled up according to this dedicated data
- the marker telling the page whether to display the data on the TOC is decided using a formula field in Airtable (basically performing a regex match looking for the client types you listed) - not sure if it's better to just hardcode into the TOC page script instead of having a dedicated field, so I just wanted to run past you in case you'd like me to adjust this behavior

**Comment by ezl** [comment]
@niall-p-gray regarding each issue:

1. renaming so that it uses the numeric value to order it - that's ok with me. i understand this may change ordering in other pages. if in the future we need an alternate ordering, we can add an extsra field for ordering. for now this is fine
2. can you screenshot the regex that is used and where the logic is so i can understand what you mean regarding this?

**Comment by ezl** [comment]
overall - behavior change on the TOC right now is a big win.

**Comment by niall-p-gray** [comment]
Hi @ezl, the toc match is a new field in the 'Clients' table as per the screenshot below... I can just as easily add into toc page scripting if you'd like one less field to worry about in the base, but I figured this allows for a little more flexibility without having to alter the page coding if you need to change anything... happy following your lead though


![Image](https://user-images.githubusercontent.com/96024810/190704414-31a06cb5-7b5a-4e45-ba89-45ad5e9843f5.png)

**Comment by ezl** [comment]
This is perfect as is. :)
